version: '3'
services:
  master:
    image: elasticsearch:5
    volumes:
     - ./es_master:/usr/share/elasticsearch/config
    ports:
     - "9200:9200"
  node1:
    image: elasticsearch:5
    volumes:
     - ./es_node1:/usr/share/elasticsearch/config
    links:
      - master:elasticsearch-master