kind: Service
apiVersion: v1
metadata:
  name: nexus-service
spec:
  selector:
    app: nexus
  type: NodePort
  ports:
  - name: nexus-8088
    protocol: TCP
    port: 8088
    nodePort: 30004
  - name: nexus-8081
    protocol: TCP
    port: 8081
    nodePort: 30005
  - name: nexus-5000
    protocol: TCP
    port: 5000
    nodePort: 30006    