apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nexus-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3
        ports:
        - containerPort: 8088
        - containerPort: 8081
        - containerPort: 5000