Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.network "public_network", auto_config: false, bridge: "en0: Wi-Fi (AirPort)"
    config.vm.provider :virtualbox do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
  
    config.vm.provision "shell", inline: <<-SHELL
      apt-get install -y virtualbox-guest-additions-iso
      apt-get install -y net-tools wget tree unzip
      echo "192.168.31.185 soft.home" >> /etc/hosts
      mkdir /root/soft
      mkdir /usr/java
      cd /usr/java 
      wget http://soft.home/jdk-8u144-linux-x64.tar.gz
      tar zvxf jdk-8u144-linux-x64.tar.gz

      JAVA_HOME=/usr/java/jdk1.8.0_144
      PATH=$PATH:$JAVA_HOME/bin:$JAVA_HOME/jre/lib 
      CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
      export JAVA_HOME PATH CLASSPATH
      echo "JAVA_HOME=/usr/java/jdk1.8.0_144" >> /root/.bash_profile
      echo "PATH=$PATH:$JAVA_HOME/bin:$JAVA_HOME/jre/lib " >> /root/.bash_profile
      echo "CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar" >> /root/.bash_profile
      echo "export JAVA_HOME PATH CLASSPATH" >> /root/.bash_profile
      chmod 600 /root/.ssh/authorized_keys
      ssh-keygen -t rsa -P "" -f /root/.ssh/id_rsa
      cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys 
      cd /home/ubuntu
      wget http://soft.home/elasticsearch-5.5.1.zip
      unzip elasticsearch-5.5.1.zip
      cd elasticsearch-5.5.1
      sed -i 's/-Xms2g/-Xms256m/' /home/ubuntu/elasticsearch-5.5.1/config/jvm.options
      sed -i 's/-Xmx2g/-Xmx256m/' /home/ubuntu/elasticsearch-5.5.1/config/jvm.options
      chown -R ubuntu:ubuntu /home/ubuntu

    SHELL
  
    config.vm.define "es_master" do |es_master|
      es_master.vm.synced_folder "data/master", "/data",owner: "root", group: "root"
      es_master.vm.provision "shell",inline:<<-SHELL
        # cp /vagrant/config/elasticsearch_master.yml /home/elasticsearch/elasticsearch-5.5.1/config/elasticsearch.yml
        # chown -R elasticsearch:elasticsearch /home/elasticsearch
      SHELL
      #config network
      es_master.vm.provision "shell",run: "always",inline:<<-SHELL
        # systemctl stop firewalld.service
        # ifconfig eth1 192.168.31.140 netmask 255.255.255.0 up
      SHELL
    end
  end