Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "public_network", auto_config: false, bridge: "en1: Wi-Fi (AirPort)"
  config.vm.provision "shell", inline: <<-SHELL
    #install base soft

 #   cp /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.bak
 #   cp /vagrant/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo



    yum install -y net-tools wget tree unzip
    #install jdk
    echo "192.168.31.185 soft.home" >> /etc/hosts
    mkdir /root/soft
    wget -O /root/soft/jdk-8u144-linux-x64.rpm http://soft.home/jdk-8u144-linux-x64.rpm
    rpm -ivh /root/soft/jdk-8u144-linux-x64.rpm
    JAVA_HOME=/usr/java/jdk1.8.0_144
    PATH=$PATH:$JAVA_HOME/bin:$JAVA_HOME/jre/lib 
    CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
    export JAVA_HOME PATH CLASSPATH
    echo "JAVA_HOME=/usr/java/jdk1.8.0_144" >> /root/.bash_profile
    echo "PATH=$PATH:$JAVA_HOME/bin:$JAVA_HOME/jre/lib " >> /root/.bash_profile
    echo "CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar" >> /root/.bash_profile
    echo "export JAVA_HOME PATH CLASSPATH" >> /root/.bash_profile
    echo "alias vim=vi" >> /root/.bash_profile
    #stop SELinux
    setenforce 0 
    sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config
    #config sshd
    echo "RSAAuthentication yes" >>/etc/ssh/sshd_config
    echo "PubkeyAuthentication yes" >>/etc/ssh/sshd_config
    sed -i 's/PasswordAuthentication\ no/PasswordAuthentication\ yes/' /etc/ssh/sshd_config
    /bin/systemctl restart  sshd.service
    mkdir -p /root/.ssh
    touch /root/.ssh/authorized_keys
    chmod 700 -R /root/.ssh
    chmod 600 /root/.ssh/authorized_keys
    ssh-keygen -t rsa -P "" -f /root/.ssh/id_rsa
    cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys 


  SHELL

  config.vm.define "hadoop_master" do |es_master|
    #download hadoop
    es_master.vm.provision "shell",inline:<<-SHELL
      mkdir -p /home/elasticsearch
      cd /home/elasticsearch
      wget http://soft.home/elasticsearch-5.5.1.zip
      unzip elasticsearch-5.5.1.zip

    SHELL
    #config network
    es_master.vm.provision "shell",run: "always",inline:<<-SHELL
      systemctl stop firewalld.service
      ifconfig eth1 192.168.31.140 netmask 255.255.255.0 up
    SHELL
  end

  #config.vm.define "hadoop_node1" do |es_node1|
  #  es_node1.vm.provision "shell",inline:<<-SHELL
  #    systemctl stop firewalld.service
  #  SHELL
  #  es_node1.vm.provision "shell",run: "always",inline:<<-SHELL
  #    ifconfig eth1 192.168.31.141 netmask 255.255.255.0 up
  #  SHELL
  #end


end
