kind: Service
apiVersion: v1
metadata:
  name: zookeeper-service
spec:
  selector:
    app: zookeeper
  type: NodePort
  ports:
  - name: zookeeper-2181
    protocol: TCP
    port: 2181
    nodePort: 30020
  - name: zookeeper-9090
    protocol: TCP
    port: 9090
    nodePort: 30021 