cluster.name: docker-application

node.name: node1
node.master: false
node.data: true

http.host: 0.0.0.0
http.port: 9200
http.cors.enabled: true
http.cors.allow-origin: "*"

discovery.zen.minimum_master_nodes: 1
discovery.zen.ping.unicast.hosts: ["172.29.0.2","172.29.0.3","172.29.0.4"]